# This plabook uses host_vars and ansible vault!
- hosts: localhost
  become: yes
  become_method: sudo

  vars:
    - name: aws_cvo_single #Please edit the name of the new CVO you want to create, host var file should match the name
  
  vars_files:
    - host_vars/{{ name }}.yml

  roles:
    - aws_configure
    - aws_cvo_single
