- hosts: localhost
  become: yes
  become_method: sudo

  vars:
    - name: aws_ansible_connector   # Enter the name of the connector, host_vars file name should match the name

  vars_files:
    - host_vars/{{ name }}.yml

  roles:
    - aws_configure
    - aws_instanceprofile      
    - aws_connector

